### ISSUE TITLE
Colors not changing

### ISSUE THREAD

**Issue by kb9zzo** [gallaux/VBEThemeColorEditor#5]
I found the VBE7.dll file and changed the scheme to the one that was included, but when I opened the VBE again, nothing had changed.  

Windows 10 64bit, Access 2016 32bit

**Comment by spike1234** [comment]
I have the same issue, with Windows 10 64bit, Access `2010` 32bit

**Comment by alefranzoni** [comment]
You've to change the colours manually after replace the dll.

The dev says:

- Open the app and edit the color palette to your liking. You can save and load palettes too (via the "Theme" menu).
- Click on "Apply theme to VBE.DLL". You will then have to select the VBE6.DLL or VBE7.DLL file depending on your Excel version. The original file will be automatically backed up in its folder.
- That's it, you have replaced the original VBE color palette with a custom one. You can now adjust your settings directly in the VBA editor (Tools > Options > Editor Format).

**Comment by jackblackmore** [comment]
@gallaux would you be able to add this information to the ReadMe please as I had the same issue?

**Comment by spike1234** [comment]
> That's it, you have replaced the original VBE color palette with a custom one. You can now adjust your settings directly in the VBA editor (Tools > Options > Editor Format).

My fault: I skipped this step!
It works fine.

Thanks

**Comment by velocity814** [comment]
For those still having issues with the colors in the VBE color palette not updating, check if you have 2 instances of VBE7.DLL.

Open command prompt and execute: `DIR C:\VBE7.DLL /S`

I had another VBE7.DLL located in `C:\Program Files (x86)\Microsoft Office\root\vfs\ProgramFilesCommonX86\Microsoft Shared\VBA\VBA7.1` - after applying the theme to that DLL, the color palette was updated accordingly.

**Comment by CSusgithub** [comment]
I only had one VBE7.dll file, but I also had trouble with the palette updating on both Win 7 & Win 10 (each with Office 16, 64bit). I use [Rubberduck ](https://rubberduckvba.wordpress.com/)on both machines so many that interferes? The regedit solution provided [here](https://github.com/gallaux/VBEThemeColorEditor/issues/2) solved my problem.
